export enum SkillCategory {
  // Technical Skills
  PROGRAMMING = "PROGRAMMING",
  BACKEND = "BACKEND",
  DATABASE = "DATABASE",
  API = "API",
  AUTHENTICATION = "AUTHENTICATION",
  VERSION_CONTROL = "VERSION_CONTROL",
  CACHING = "CACHING",
  CONTAINERIZATION = "CONTAINERIZATION",
  TESTING = "TESTING",
  DEPLOYMENT = "DEPLOYMENT",
  SECURITY = "SECURITY",

  // Computer Science Fundamentals
  DATA_STRUCTURES = "DATA_STRUCTURES",
  ALGORITHMS = "ALGORITHMS",
  OBJECT_ORIENTED_PROGRAMMING = "OBJECT_ORIENTED_PROGRAMMING",
  DBMS = "DBMS",
  OPERATING_SYSTEM = "OPERATING_SYSTEM",
  COMPUTER_NETWORKS = "COMPUTER_NETWORKS",

  // Placement Preparation
  APTITUDE = "APTITUDE",
  LOGICAL_REASONING = "LOGICAL_REASONING",
  VERBAL_ABILITY = "VERBAL_ABILITY",

  // Communication
  ENGLISH_COMMUNICATION = "ENGLISH_COMMUNICATION",
  HR_INTERVIEW = "HR_INTERVIEW",

  // Professional Skills
  PROFESSIONAL = "PROFESSIONAL",
}

export enum SkillDifficulty {
  BEGINNER = "beginner",

  INTERMEDIATE = "intermediate",

  ADVANCED = "advanced",
}